/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicantsList {
    #[serde(rename = "applicants", skip_serializing_if = "Option::is_none")]
    pub applicants: Option<Vec<crate::models::Applicant>>,
}

impl ApplicantsList {
    pub fn new() -> ApplicantsList {
        ApplicantsList { applicants: None }
    }
}
