/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Applicant {
    /// The unique identifier for the applicant. Read-only.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The date and time when this applicant was created. Read-only.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The date and time when this applicant is scheduled to be deleted. Read-only.
    #[serde(rename = "delete_at", skip_serializing_if = "Option::is_none")]
    pub delete_at: Option<String>,
    /// The uri of this resource. Read-only.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// Read-only.
    #[serde(rename = "sandbox", skip_serializing_if = "Option::is_none")]
    pub sandbox: Option<bool>,
    /// The applicant’s first name
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// The applicant’s surname
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// The applicant’s email address. Required if doing a US check, or a UK check for which `applicant_provides_data` is `true`.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The applicant’s date of birth
    #[serde(rename = "dob", skip_serializing_if = "Option::is_none")]
    pub dob: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<crate::models::Address>>,
    #[serde(rename = "id_numbers", skip_serializing_if = "Option::is_none")]
    pub id_numbers: Option<Vec<crate::models::IdNumber>>,
}

impl Applicant {
    pub fn new() -> Applicant {
        Applicant {
            id: None,
            created_at: None,
            delete_at: None,
            href: None,
            sandbox: None,
            first_name: None,
            last_name: None,
            email: None,
            dob: None,
            address: None,
            id_numbers: None,
        }
    }
}
