/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownIssuingAuthorityBreakdownNfcPassiveAuthentication : Asserts whether the document NFC chip data was tampered.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownIssuingAuthorityBreakdownNfcPassiveAuthentication {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl DocumentBreakdownIssuingAuthorityBreakdownNfcPassiveAuthentication {
    /// Asserts whether the document NFC chip data was tampered.
    pub fn new() -> DocumentBreakdownIssuingAuthorityBreakdownNfcPassiveAuthentication {
        DocumentBreakdownIssuingAuthorityBreakdownNfcPassiveAuthentication {
            result: None,
            properties: None,
        }
    }
}
