/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownImageIntegrityBreakdownImageQuality : Asserts whether the quality of the image was sufficient for processing.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownImageIntegrityBreakdownImageQuality {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<crate::models::DocumentIqReasons>>,
}

impl DocumentBreakdownImageIntegrityBreakdownImageQuality {
    /// Asserts whether the quality of the image was sufficient for processing.
    pub fn new() -> DocumentBreakdownImageIntegrityBreakdownImageQuality {
        DocumentBreakdownImageIntegrityBreakdownImageQuality {
            result: None,
            properties: None,
        }
    }
}
