/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownImageIntegrityBreakdown {
    #[serde(rename = "image_quality", skip_serializing_if = "Option::is_none")]
    pub image_quality:
        Option<Box<crate::models::DocumentBreakdownImageIntegrityBreakdownImageQuality>>,
    #[serde(rename = "supported_document", skip_serializing_if = "Option::is_none")]
    pub supported_document:
        Option<Box<crate::models::DocumentBreakdownImageIntegrityBreakdownSupportedDocument>>,
    #[serde(rename = "colour_picture", skip_serializing_if = "Option::is_none")]
    pub colour_picture:
        Option<Box<crate::models::DocumentBreakdownImageIntegrityBreakdownColourPicture>>,
    #[serde(
        rename = "conclusive_document_quality",
        skip_serializing_if = "Option::is_none"
    )]
    pub conclusive_document_quality: Option<
        Box<crate::models::DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality>,
    >,
}

impl DocumentBreakdownImageIntegrityBreakdown {
    pub fn new() -> DocumentBreakdownImageIntegrityBreakdown {
        DocumentBreakdownImageIntegrityBreakdown {
            image_quality: None,
            supported_document: None,
            colour_picture: None,
            conclusive_document_quality: None,
        }
    }
}
