/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownVisualAuthenticityBreakdownFaceDetection : No face was detected on the document.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownVisualAuthenticityBreakdownFaceDetection {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl DocumentBreakdownVisualAuthenticityBreakdownFaceDetection {
    /// No face was detected on the document.
    pub fn new() -> DocumentBreakdownVisualAuthenticityBreakdownFaceDetection {
        DocumentBreakdownVisualAuthenticityBreakdownFaceDetection {
            result: None,
            properties: None,
        }
    }
}
