/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownDataValidationBreakdownDocumentExpiration : If this is flagged, the document has expired.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownDataValidationBreakdownDocumentExpiration {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl DocumentBreakdownDataValidationBreakdownDocumentExpiration {
    /// If this is flagged, the document has expired.
    pub fn new() -> DocumentBreakdownDataValidationBreakdownDocumentExpiration {
        DocumentBreakdownDataValidationBreakdownDocumentExpiration {
            result: None,
            properties: None,
        }
    }
}
