/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownIssuingAuthorityBreakdownNfcActiveAuthentication : Asserts whether the document NFC chip is original or cloned.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownIssuingAuthorityBreakdownNfcActiveAuthentication {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl DocumentBreakdownIssuingAuthorityBreakdownNfcActiveAuthentication {
    /// Asserts whether the document NFC chip is original or cloned.
    pub fn new() -> DocumentBreakdownIssuingAuthorityBreakdownNfcActiveAuthentication {
        DocumentBreakdownIssuingAuthorityBreakdownNfcActiveAuthentication {
            result: None,
            properties: None,
        }
    }
}
