/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownImageIntegrityBreakdownSupportedDocument : Asserts whether the submitted document is supported.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownImageIntegrityBreakdownSupportedDocument {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl DocumentBreakdownImageIntegrityBreakdownSupportedDocument {
    /// Asserts whether the submitted document is supported.
    pub fn new() -> DocumentBreakdownImageIntegrityBreakdownSupportedDocument {
        DocumentBreakdownImageIntegrityBreakdownSupportedDocument {
            result: None,
            properties: None,
        }
    }
}
