/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownImageIntegrity : Asserts if the document is of sufficient quality to verify.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownImageIntegrity {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::DocumentBreakdownImageIntegrityBreakdown>>,
}

impl DocumentBreakdownImageIntegrity {
    /// Asserts if the document is of sufficient quality to verify.
    pub fn new() -> DocumentBreakdownImageIntegrity {
        DocumentBreakdownImageIntegrity {
            result: None,
            breakdown: None,
        }
    }
}
