/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownVisualAuthenticityBreakdownDigitalTampering : Indication of digital tampering in the image.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownVisualAuthenticityBreakdownDigitalTampering {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl DocumentBreakdownVisualAuthenticityBreakdownDigitalTampering {
    /// Indication of digital tampering in the image.
    pub fn new() -> DocumentBreakdownVisualAuthenticityBreakdownDigitalTampering {
        DocumentBreakdownVisualAuthenticityBreakdownDigitalTampering {
            result: None,
            properties: None,
        }
    }
}
