/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownVisualAuthenticityBreakdownSecurityFeatures : Security features expected on the document are missing or wrong.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownVisualAuthenticityBreakdownSecurityFeatures {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl DocumentBreakdownVisualAuthenticityBreakdownSecurityFeatures {
    /// Security features expected on the document are missing or wrong.
    pub fn new() -> DocumentBreakdownVisualAuthenticityBreakdownSecurityFeatures {
        DocumentBreakdownVisualAuthenticityBreakdownSecurityFeatures {
            result: None,
            properties: None,
        }
    }
}
