/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentPropertiesDrivingLicenceInformation {
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "obtainment_date", skip_serializing_if = "Option::is_none")]
    pub obtainment_date: Option<String>,
    #[serde(rename = "expiry_date", skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<String>,
    #[serde(rename = "codes", skip_serializing_if = "Option::is_none")]
    pub codes: Option<String>,
}

impl DocumentPropertiesDrivingLicenceInformation {
    pub fn new() -> DocumentPropertiesDrivingLicenceInformation {
        DocumentPropertiesDrivingLicenceInformation {
            category: None,
            obtainment_date: None,
            expiry_date: None,
            codes: None,
        }
    }
}
