/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownPoliceRecord : Asserts whether the document had been identified as lost, stolen or otherwise compromised.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownPoliceRecord {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl DocumentBreakdownPoliceRecord {
    /// Asserts whether the document had been identified as lost, stolen or otherwise compromised.
    pub fn new() -> DocumentBreakdownPoliceRecord {
        DocumentBreakdownPoliceRecord { result: None }
    }
}
