/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownIssuingAuthority : Asserts whether data on the document matches the issuing authority data.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownIssuingAuthority {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::DocumentBreakdownIssuingAuthorityBreakdown>>,
}

impl DocumentBreakdownIssuingAuthority {
    /// Asserts whether data on the document matches the issuing authority data.
    pub fn new() -> DocumentBreakdownIssuingAuthority {
        DocumentBreakdownIssuingAuthority {
            result: None,
            breakdown: None,
        }
    }
}
