/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownVisualAuthenticityBreakdownFonts : Fonts in the document don’t match the expected ones.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownVisualAuthenticityBreakdownFonts {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl DocumentBreakdownVisualAuthenticityBreakdownFonts {
    /// Fonts in the document don’t match the expected ones.
    pub fn new() -> DocumentBreakdownVisualAuthenticityBreakdownFonts {
        DocumentBreakdownVisualAuthenticityBreakdownFonts {
            result: None,
            properties: None,
        }
    }
}
