/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownVisualAuthenticityBreakdownPictureFaceIntegrity : The pictures of the person identified on the document show signs of tampering or alteration.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownVisualAuthenticityBreakdownPictureFaceIntegrity {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl DocumentBreakdownVisualAuthenticityBreakdownPictureFaceIntegrity {
    /// The pictures of the person identified on the document show signs of tampering or alteration.
    pub fn new() -> DocumentBreakdownVisualAuthenticityBreakdownPictureFaceIntegrity {
        DocumentBreakdownVisualAuthenticityBreakdownPictureFaceIntegrity {
            result: None,
            properties: None,
        }
    }
}
