/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownDataComparison : Asserts whether data on the document is consistent with data provided when creating an applicant through the API.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownDataComparison {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::DocumentBreakdownDataComparisonBreakdown>>,
}

impl DocumentBreakdownDataComparison {
    /// Asserts whether data on the document is consistent with data provided when creating an applicant through the API.
    pub fn new() -> DocumentBreakdownDataComparison {
        DocumentBreakdownDataComparison {
            result: None,
            breakdown: None,
        }
    }
}
