/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentPropertiesDocumentClassification {
    #[serde(rename = "issuing_country", skip_serializing_if = "Option::is_none")]
    pub issuing_country: Option<String>,
    #[serde(rename = "document_type", skip_serializing_if = "Option::is_none")]
    pub document_type: Option<String>,
    #[serde(rename = "issuing_state", skip_serializing_if = "Option::is_none")]
    pub issuing_state: Option<String>,
}

impl DocumentPropertiesDocumentClassification {
    pub fn new() -> DocumentPropertiesDocumentClassification {
        DocumentPropertiesDocumentClassification {
            issuing_country: None,
            document_type: None,
            issuing_state: None,
        }
    }
}
