/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownVisualAuthenticityBreakdown {
    #[serde(rename = "fonts", skip_serializing_if = "Option::is_none")]
    pub fonts: Option<Box<crate::models::DocumentBreakdownVisualAuthenticityBreakdownFonts>>,
    #[serde(
        rename = "picture_face_integrity",
        skip_serializing_if = "Option::is_none"
    )]
    pub picture_face_integrity: Option<
        Box<crate::models::DocumentBreakdownVisualAuthenticityBreakdownPictureFaceIntegrity>,
    >,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<crate::models::DocumentBreakdownVisualAuthenticityBreakdownTemplate>>,
    #[serde(rename = "security_features", skip_serializing_if = "Option::is_none")]
    pub security_features:
        Option<Box<crate::models::DocumentBreakdownVisualAuthenticityBreakdownSecurityFeatures>>,
    #[serde(
        rename = "original_document_present",
        skip_serializing_if = "Option::is_none"
    )]
    pub original_document_present: Option<
        Box<crate::models::DocumentBreakdownVisualAuthenticityBreakdownOriginalDocumentPresent>,
    >,
    #[serde(rename = "digital_tampering", skip_serializing_if = "Option::is_none")]
    pub digital_tampering:
        Option<Box<crate::models::DocumentBreakdownVisualAuthenticityBreakdownDigitalTampering>>,
    #[serde(rename = "other", skip_serializing_if = "Option::is_none")]
    pub other: Option<Box<crate::models::DocumentBreakdownVisualAuthenticityBreakdownOther>>,
    #[serde(rename = "face_detection", skip_serializing_if = "Option::is_none")]
    pub face_detection:
        Option<Box<crate::models::DocumentBreakdownVisualAuthenticityBreakdownFaceDetection>>,
}

impl DocumentBreakdownVisualAuthenticityBreakdown {
    pub fn new() -> DocumentBreakdownVisualAuthenticityBreakdown {
        DocumentBreakdownVisualAuthenticityBreakdown {
            fonts: None,
            picture_face_integrity: None,
            template: None,
            security_features: None,
            original_document_present: None,
            digital_tampering: None,
            other: None,
            face_detection: None,
        }
    }
}
