/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownIssuingAuthorityBreakdown {
    #[serde(
        rename = "nfc_active_authentication",
        skip_serializing_if = "Option::is_none"
    )]
    pub nfc_active_authentication: Option<
        Box<crate::models::DocumentBreakdownIssuingAuthorityBreakdownNfcActiveAuthentication>,
    >,
    #[serde(
        rename = "nfc_passive_authentication",
        skip_serializing_if = "Option::is_none"
    )]
    pub nfc_passive_authentication: Option<
        Box<crate::models::DocumentBreakdownIssuingAuthorityBreakdownNfcPassiveAuthentication>,
    >,
}

impl DocumentBreakdownIssuingAuthorityBreakdown {
    pub fn new() -> DocumentBreakdownIssuingAuthorityBreakdown {
        DocumentBreakdownIssuingAuthorityBreakdown {
            nfc_active_authentication: None,
            nfc_passive_authentication: None,
        }
    }
}
