/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality : Asserts if the document was of enough quality to be able to perform a fraud inspection.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<crate::models::DocumentCdqReasons>>,
}

impl DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality {
    /// Asserts if the document was of enough quality to be able to perform a fraud inspection.
    pub fn new() -> DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality {
        DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality {
            result: None,
            properties: None,
        }
    }
}
