/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownDataConsistency : Asserts whether data represented in multiple places on the document is consistent.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownDataConsistency {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::DocumentBreakdownDataConsistencyBreakdown>>,
}

impl DocumentBreakdownDataConsistency {
    /// Asserts whether data represented in multiple places on the document is consistent.
    pub fn new() -> DocumentBreakdownDataConsistency {
        DocumentBreakdownDataConsistency {
            result: None,
            breakdown: None,
        }
    }
}
