/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentOdpReasons {
    /// When the applicant's document is on a physical screen or device.
    #[serde(rename = "photo_of_screen", skip_serializing_if = "Option::is_none")]
    pub photo_of_screen: Option<String>,
    /// When the applicant has used their mobile phone, tablet, or computer to take a photo within the device.
    #[serde(rename = "screenshot", skip_serializing_if = "Option::is_none")]
    pub screenshot: Option<String>,
    /// When the applicant has previously captured an image of the document, printed it out, and has now taken a photo of this print out to upload.
    #[serde(
        rename = "document_on_printed_paper",
        skip_serializing_if = "Option::is_none"
    )]
    pub document_on_printed_paper: Option<String>,
    /// When the document has clearly been captured using a scanner and there are visible indicators of this
    #[serde(rename = "scan", skip_serializing_if = "Option::is_none")]
    pub scan: Option<String>,
}

impl DocumentOdpReasons {
    pub fn new() -> DocumentOdpReasons {
        DocumentOdpReasons {
            photo_of_screen: None,
            screenshot: None,
            document_on_printed_paper: None,
            scan: None,
        }
    }
}
