/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DocumentBreakdownCompromisedDocument : Asserts whether the image of the document has been found in our internal database of compromised documents.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DocumentBreakdownCompromisedDocument {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl DocumentBreakdownCompromisedDocument {
    /// Asserts whether the image of the document has been found in our internal database of compromised documents.
    pub fn new() -> DocumentBreakdownCompromisedDocument {
        DocumentBreakdownCompromisedDocument { result: None }
    }
}
