/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected : Asserts whether the numbers and head movements were correctly executed.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected {
    /// Asserts whether the numbers and head movements were correctly executed.
    pub fn new() -> FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected {
        FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected {
            result: None,
            properties: None,
        }
    }
}
