/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityVideoBreakdownVisualAuthenticityBreakdown {
    #[serde(rename = "liveness_detected", skip_serializing_if = "Option::is_none")]
    pub liveness_detected: Option<Box<crate::models::FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownLivenessDetected>>,
    #[serde(rename = "spoofing_detection", skip_serializing_if = "Option::is_none")]
    pub spoofing_detection: Option<Box<crate::models::FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownSpoofingDetection>>,
}

impl FacialSimilarityVideoBreakdownVisualAuthenticityBreakdown {
    pub fn new() -> FacialSimilarityVideoBreakdownVisualAuthenticityBreakdown {
        FacialSimilarityVideoBreakdownVisualAuthenticityBreakdown {
            liveness_detected: None,
            spoofing_detection: None,
        }
    }
}
