/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties {
    /// A floating point number between 0 and 1 that expresses how similar the two faces are, where 1 is a perfect match.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
}

impl FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties {
    pub fn new() -> FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties {
        FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties { score: None }
    }
}
