/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetection : Contains a score value under the properties bag.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetection {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<crate::models::FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetectionProperties>>,
}

impl FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetection {
    /// Contains a score value under the properties bag.
    pub fn new() -> FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetection {
        FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetection {
            result: None,
            properties: None,
        }
    }
}
