/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FacialSimilarityVideoBreakdownVisualAuthenticity : Asserts whether the person in the live video is real (not a spoof) and live.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityVideoBreakdownVisualAuthenticity {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown:
        Option<Box<crate::models::FacialSimilarityVideoBreakdownVisualAuthenticityBreakdown>>,
}

impl FacialSimilarityVideoBreakdownVisualAuthenticity {
    /// Asserts whether the person in the live video is real (not a spoof) and live.
    pub fn new() -> FacialSimilarityVideoBreakdownVisualAuthenticity {
        FacialSimilarityVideoBreakdownVisualAuthenticity {
            result: None,
            breakdown: None,
        }
    }
}
