/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FacialSimilarityPhotoBreakdownVisualAuthenticity : Asserts whether the person in the live photo is real and not a spoof.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityPhotoBreakdownVisualAuthenticity {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown:
        Option<Box<crate::models::FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdown>>,
}

impl FacialSimilarityPhotoBreakdownVisualAuthenticity {
    /// Asserts whether the person in the live photo is real and not a spoof.
    pub fn new() -> FacialSimilarityPhotoBreakdownVisualAuthenticity {
        FacialSimilarityPhotoBreakdownVisualAuthenticity {
            result: None,
            breakdown: None,
        }
    }
}
