/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityPhotoBreakdownImageIntegrityBreakdown {
    #[serde(rename = "face_detected", skip_serializing_if = "Option::is_none")]
    pub face_detected: Option<
        Box<crate::models::FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected>,
    >,
    #[serde(rename = "source_integrity", skip_serializing_if = "Option::is_none")]
    pub source_integrity: Option<
        Box<crate::models::FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity>,
    >,
}

impl FacialSimilarityPhotoBreakdownImageIntegrityBreakdown {
    pub fn new() -> FacialSimilarityPhotoBreakdownImageIntegrityBreakdown {
        FacialSimilarityPhotoBreakdownImageIntegrityBreakdown {
            face_detected: None,
            source_integrity: None,
        }
    }
}
