/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties {
    /// A floating point number between 0 and 1 that expresses how similar the two faces are, where 1 is a perfect match.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    /// The UUID for the document containing the extracted face that was used for face matching.
    #[serde(rename = "document_id", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
}

impl FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties {
    pub fn new() -> FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties {
        FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatchProperties {
            score: None,
            document_id: None,
        }
    }
}
