/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownSpoofingDetection : Asserts whether the live video is not a spoof (such as videos of digital screens).

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownSpoofingDetection {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<crate::models::FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetectionProperties>>,
}

impl FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownSpoofingDetection {
    /// Asserts whether the live video is not a spoof (such as videos of digital screens).
    pub fn new() -> FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownSpoofingDetection {
        FacialSimilarityVideoBreakdownVisualAuthenticityBreakdownSpoofingDetection {
            result: None,
            properties: None,
        }
    }
}
