/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity : Asserts whether the live video is trustworthy - e.g. not from a fake webcam.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<crate::models::VideoReasons>>,
}

impl FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity {
    /// Asserts whether the live video is trustworthy - e.g. not from a fake webcam.
    pub fn new() -> FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity {
        FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity {
            result: None,
            properties: None,
        }
    }
}
