/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FacialSimilarityVideoBreakdownFaceComparison : Asserts whether the face in the document matches the face in the live video.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityVideoBreakdownFaceComparison {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown:
        Option<Box<crate::models::FacialSimilarityPhotoBreakdownFaceComparisonBreakdown>>,
}

impl FacialSimilarityVideoBreakdownFaceComparison {
    /// Asserts whether the face in the document matches the face in the live video.
    pub fn new() -> FacialSimilarityVideoBreakdownFaceComparison {
        FacialSimilarityVideoBreakdownFaceComparison {
            result: None,
            breakdown: None,
        }
    }
}
