/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityPhotoBreakdownFaceComparisonBreakdown {
    #[serde(rename = "face_match", skip_serializing_if = "Option::is_none")]
    pub face_match:
        Option<Box<crate::models::FacialSimilarityPhotoBreakdownFaceComparisonBreakdownFaceMatch>>,
}

impl FacialSimilarityPhotoBreakdownFaceComparisonBreakdown {
    pub fn new() -> FacialSimilarityPhotoBreakdownFaceComparisonBreakdown {
        FacialSimilarityPhotoBreakdownFaceComparisonBreakdown { face_match: None }
    }
}
