/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityPhotoBreakdown {
    #[serde(rename = "face_comparison", skip_serializing_if = "Option::is_none")]
    pub face_comparison: Option<Box<crate::models::FacialSimilarityPhotoBreakdownFaceComparison>>,
    #[serde(rename = "image_integrity", skip_serializing_if = "Option::is_none")]
    pub image_integrity: Option<Box<crate::models::FacialSimilarityPhotoBreakdownImageIntegrity>>,
    #[serde(
        rename = "visual_authenticity",
        skip_serializing_if = "Option::is_none"
    )]
    pub visual_authenticity:
        Option<Box<crate::models::FacialSimilarityPhotoBreakdownVisualAuthenticity>>,
}

impl FacialSimilarityPhotoBreakdown {
    pub fn new() -> FacialSimilarityPhotoBreakdown {
        FacialSimilarityPhotoBreakdown {
            face_comparison: None,
            image_integrity: None,
            visual_authenticity: None,
        }
    }
}
