/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdown {
    #[serde(rename = "spoofing_detection", skip_serializing_if = "Option::is_none")]
    pub spoofing_detection: Option<Box<crate::models::FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdownSpoofingDetection>>,
}

impl FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdown {
    pub fn new() -> FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdown {
        FacialSimilarityPhotoBreakdownVisualAuthenticityBreakdown {
            spoofing_detection: None,
        }
    }
}
