/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdown {
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Box<crate::models::IdentityEnhancedBreakdownSources>>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<crate::models::IdentityEnhancedBreakdownAddress>>,
    #[serde(rename = "date_of_birth", skip_serializing_if = "Option::is_none")]
    pub date_of_birth: Option<Box<crate::models::IdentityEnhancedBreakdownDateOfBirth>>,
    #[serde(rename = "mortality", skip_serializing_if = "Option::is_none")]
    pub mortality: Option<Box<crate::models::IdentityEnhancedBreakdownMortality>>,
}

impl IdentityEnhancedBreakdown {
    pub fn new() -> IdentityEnhancedBreakdown {
        IdentityEnhancedBreakdown {
            sources: None,
            address: None,
            date_of_birth: None,
            mortality: None,
        }
    }
}
