/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// IdentityEnhancedBreakdownDateOfBirthBreakdownVotingRegister : Date of birth match against voting register.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownDateOfBirthBreakdownVotingRegister {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl IdentityEnhancedBreakdownDateOfBirthBreakdownVotingRegister {
    /// Date of birth match against voting register.
    pub fn new() -> IdentityEnhancedBreakdownDateOfBirthBreakdownVotingRegister {
        IdentityEnhancedBreakdownDateOfBirthBreakdownVotingRegister {
            result: None,
            properties: None,
        }
    }
}
