/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// IdentityEnhancedBreakdownAddress : Asserts if the applicant's address matches any sources.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownAddress {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::IdentityEnhancedBreakdownAddressBreakdown>>,
}

impl IdentityEnhancedBreakdownAddress {
    /// Asserts if the applicant's address matches any sources.
    pub fn new() -> IdentityEnhancedBreakdownAddress {
        IdentityEnhancedBreakdownAddress {
            result: None,
            breakdown: None,
        }
    }
}
