/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// IdentityEnhancedBreakdownDateOfBirth : Asserts if the applicant's date of birth matches any sources.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownDateOfBirth {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::IdentityEnhancedBreakdownDateOfBirthBreakdown>>,
}

impl IdentityEnhancedBreakdownDateOfBirth {
    /// Asserts if the applicant's date of birth matches any sources.
    pub fn new() -> IdentityEnhancedBreakdownDateOfBirth {
        IdentityEnhancedBreakdownDateOfBirth {
            result: None,
            breakdown: None,
        }
    }
}
