/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownAddressBreakdownCreditAgenciesProperties {
    #[serde(rename = "number_of_matches", skip_serializing_if = "Option::is_none")]
    pub number_of_matches: Option<i32>,
}

impl IdentityEnhancedBreakdownAddressBreakdownCreditAgenciesProperties {
    pub fn new() -> IdentityEnhancedBreakdownAddressBreakdownCreditAgenciesProperties {
        IdentityEnhancedBreakdownAddressBreakdownCreditAgenciesProperties {
            number_of_matches: None,
        }
    }
}
