/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// IdentityEnhancedBreakdownMortality : Asserts if the applicant's details match any death records.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownMortality {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl IdentityEnhancedBreakdownMortality {
    /// Asserts if the applicant's details match any death records.
    pub fn new() -> IdentityEnhancedBreakdownMortality {
        IdentityEnhancedBreakdownMortality { result: None }
    }
}
