/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// IdentityEnhancedBreakdownAddressBreakdownCreditAgencies : The number of address matches against credit agencies.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownAddressBreakdownCreditAgencies {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<
        Box<crate::models::IdentityEnhancedBreakdownAddressBreakdownCreditAgenciesProperties>,
    >,
}

impl IdentityEnhancedBreakdownAddressBreakdownCreditAgencies {
    /// The number of address matches against credit agencies.
    pub fn new() -> IdentityEnhancedBreakdownAddressBreakdownCreditAgencies {
        IdentityEnhancedBreakdownAddressBreakdownCreditAgencies {
            result: None,
            properties: None,
        }
    }
}
