/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedProperties {
    /// Returns address number which has been matched.
    #[serde(rename = "matched_address", skip_serializing_if = "Option::is_none")]
    pub matched_address: Option<f32>,
    /// Returns array of sources which contain matched addresses for the corresponding address number.
    #[serde(rename = "matched_addresses", skip_serializing_if = "Option::is_none")]
    pub matched_addresses: Option<Vec<crate::models::IdentityEnhancedPropertiesMatchedAddresses>>,
}

impl IdentityEnhancedProperties {
    pub fn new() -> IdentityEnhancedProperties {
        IdentityEnhancedProperties {
            matched_address: None,
            matched_addresses: None,
        }
    }
}
