/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties {
    #[serde(
        rename = "total_number_of_sources",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_number_of_sources: Option<i32>,
}

impl IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties {
    pub fn new() -> IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties {
        IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties {
            total_number_of_sources: None,
        }
    }
}
