/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownSourcesBreakdown {
    #[serde(rename = "total_sources", skip_serializing_if = "Option::is_none")]
    pub total_sources:
        Option<Box<crate::models::IdentityEnhancedBreakdownSourcesBreakdownTotalSources>>,
}

impl IdentityEnhancedBreakdownSourcesBreakdown {
    pub fn new() -> IdentityEnhancedBreakdownSourcesBreakdown {
        IdentityEnhancedBreakdownSourcesBreakdown {
            total_sources: None,
        }
    }
}
