/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownDateOfBirthBreakdown {
    #[serde(rename = "credit_agencies", skip_serializing_if = "Option::is_none")]
    pub credit_agencies:
        Option<Box<crate::models::IdentityEnhancedBreakdownDateOfBirthBreakdownCreditAgencies>>,
    #[serde(rename = "voting_register", skip_serializing_if = "Option::is_none")]
    pub voting_register:
        Option<Box<crate::models::IdentityEnhancedBreakdownDateOfBirthBreakdownVotingRegister>>,
}

impl IdentityEnhancedBreakdownDateOfBirthBreakdown {
    pub fn new() -> IdentityEnhancedBreakdownDateOfBirthBreakdown {
        IdentityEnhancedBreakdownDateOfBirthBreakdown {
            credit_agencies: None,
            voting_register: None,
        }
    }
}
