/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// IdentityEnhancedBreakdownAddressBreakdownTelephoneDatabase : Address match against telephone database.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedBreakdownAddressBreakdownTelephoneDatabase {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl IdentityEnhancedBreakdownAddressBreakdownTelephoneDatabase {
    /// Address match against telephone database.
    pub fn new() -> IdentityEnhancedBreakdownAddressBreakdownTelephoneDatabase {
        IdentityEnhancedBreakdownAddressBreakdownTelephoneDatabase {
            result: None,
            properties: None,
        }
    }
}
