/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityEnhancedPropertiesMatchedAddresses {
    /// The address number.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f32>,
    /// Sources which contain matched addresses.
    #[serde(rename = "match_types", skip_serializing_if = "Option::is_none")]
    pub match_types: Option<Vec<String>>,
}

impl IdentityEnhancedPropertiesMatchedAddresses {
    pub fn new() -> IdentityEnhancedPropertiesMatchedAddresses {
        IdentityEnhancedPropertiesMatchedAddresses {
            id: None,
            match_types: None,
        }
    }
}
