/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// KnownFacesBreakdownImageIntegrity : Asserts whether the uploaded live photo or live video and the content contained within it were of sufficient quality to perform a face comparison.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KnownFacesBreakdownImageIntegrity {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl KnownFacesBreakdownImageIntegrity {
    /// Asserts whether the uploaded live photo or live video and the content contained within it were of sufficient quality to perform a face comparison.
    pub fn new() -> KnownFacesBreakdownImageIntegrity {
        KnownFacesBreakdownImageIntegrity { result: None }
    }
}
