/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KnownFacesBreakdown {
    #[serde(
        rename = "previously_seen_faces",
        skip_serializing_if = "Option::is_none"
    )]
    pub previously_seen_faces: Option<Box<crate::models::KnownFacesBreakdownPreviouslySeenFaces>>,
    #[serde(rename = "image_integrity", skip_serializing_if = "Option::is_none")]
    pub image_integrity: Option<Box<crate::models::KnownFacesBreakdownImageIntegrity>>,
}

impl KnownFacesBreakdown {
    pub fn new() -> KnownFacesBreakdown {
        KnownFacesBreakdown {
            previously_seen_faces: None,
            image_integrity: None,
        }
    }
}
