/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KnownFacesProperties {
    /// Returns any matching applicant IDs as entries inside a matches array under a properties bag.
    #[serde(rename = "matches", skip_serializing_if = "Option::is_none")]
    pub matches: Option<Vec<crate::models::KnownFacesPropertiesMatches>>,
}

impl KnownFacesProperties {
    pub fn new() -> KnownFacesProperties {
        KnownFacesProperties { matches: None }
    }
}
