/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// KnownFacesBreakdownPreviouslySeenFaces : Asserts whether the applicant's most recent facial media (live photo or live video) matches any other live photos or live videos already in your Onfido account database.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KnownFacesBreakdownPreviouslySeenFaces {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl KnownFacesBreakdownPreviouslySeenFaces {
    /// Asserts whether the applicant's most recent facial media (live photo or live video) matches any other live photos or live videos already in your Onfido account database.
    pub fn new() -> KnownFacesBreakdownPreviouslySeenFaces {
        KnownFacesBreakdownPreviouslySeenFaces { result: None }
    }
}
