/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LivePhotosList {
    #[serde(rename = "live_photos", skip_serializing_if = "Option::is_none")]
    pub live_photos: Option<Vec<crate::models::LivePhoto>>,
}

impl LivePhotosList {
    pub fn new() -> LivePhotosList {
        LivePhotosList { live_photos: None }
    }
}
