/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LiveVideosList {
    #[serde(rename = "live_videos", skip_serializing_if = "Option::is_none")]
    pub live_videos: Option<Vec<crate::models::LiveVideo>>,
}

impl LiveVideosList {
    pub fn new() -> LiveVideosList {
        LiveVideosList { live_videos: None }
    }
}
