/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PhotoFullyAutoBreakdownImageIntegrity : Asserts whether the quality and integrity of the uploaded files were sufficient to perform a face comparison.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PhotoFullyAutoBreakdownImageIntegrity {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::PhotoFullyAutoBreakdownImageIntegrityBreakdown>>,
}

impl PhotoFullyAutoBreakdownImageIntegrity {
    /// Asserts whether the quality and integrity of the uploaded files were sufficient to perform a face comparison.
    pub fn new() -> PhotoFullyAutoBreakdownImageIntegrity {
        PhotoFullyAutoBreakdownImageIntegrity {
            result: None,
            breakdown: None,
        }
    }
}
