/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ProofOfAddressBreakdownImageIntegrity : Asserts whether the quality of the uploaded document was sufficient to verify the address.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProofOfAddressBreakdownImageIntegrity {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::ProofOfAddressBreakdownImageIntegrityBreakdown>>,
}

impl ProofOfAddressBreakdownImageIntegrity {
    /// Asserts whether the quality of the uploaded document was sufficient to verify the address.
    pub fn new() -> ProofOfAddressBreakdownImageIntegrity {
        ProofOfAddressBreakdownImageIntegrity {
            result: None,
            breakdown: None,
        }
    }
}
