/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProofOfAddressBreakdownDocumentClassificationBreakdown {
    #[serde(rename = "supported_document", skip_serializing_if = "Option::is_none")]
    pub supported_document:
        Option<Box<crate::models::DocumentBreakdownDataComparisonBreakdownIssuingCountry>>,
}

impl ProofOfAddressBreakdownDocumentClassificationBreakdown {
    pub fn new() -> ProofOfAddressBreakdownDocumentClassificationBreakdown {
        ProofOfAddressBreakdownDocumentClassificationBreakdown {
            supported_document: None,
        }
    }
}
