/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProofOfAddressProperties {
    /// This property provides the address on the document.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// This property provides the document type according to the set of supported documents.
    #[serde(rename = "document_type", skip_serializing_if = "Option::is_none")]
    pub document_type: Option<String>,
    /// This property provides the first names on the document, including any initials and middle names.
    #[serde(rename = "first_names", skip_serializing_if = "Option::is_none")]
    pub first_names: Option<String>,
    /// This property provided the last names on the document.
    #[serde(rename = "last_names", skip_serializing_if = "Option::is_none")]
    pub last_names: Option<String>,
    /// This property provides the issue date of the document.
    #[serde(rename = "issue_date", skip_serializing_if = "Option::is_none")]
    pub issue_date: Option<String>,
    /// This property provides the document issuer (e.g. HSBC, British Gas).
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    /// This property provides the summary period start date.
    #[serde(
        rename = "summary_period_start",
        skip_serializing_if = "Option::is_none"
    )]
    pub summary_period_start: Option<String>,
    /// This property provides the summary period end date.
    #[serde(rename = "summary_period_end", skip_serializing_if = "Option::is_none")]
    pub summary_period_end: Option<String>,
}

impl ProofOfAddressProperties {
    pub fn new() -> ProofOfAddressProperties {
        ProofOfAddressProperties {
            address: None,
            document_type: None,
            first_names: None,
            last_names: None,
            issue_date: None,
            issuer: None,
            summary_period_start: None,
            summary_period_end: None,
        }
    }
}
