/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProofOfAddressBreakdownDataComparisonBreakdown {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<crate::models::DocumentBreakdownDataComparisonBreakdownIssuingCountry>>,
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name:
        Option<Box<crate::models::DocumentBreakdownDataComparisonBreakdownIssuingCountry>>,
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name:
        Option<Box<crate::models::DocumentBreakdownDataComparisonBreakdownIssuingCountry>>,
}

impl ProofOfAddressBreakdownDataComparisonBreakdown {
    pub fn new() -> ProofOfAddressBreakdownDataComparisonBreakdown {
        ProofOfAddressBreakdownDataComparisonBreakdown {
            address: None,
            first_name: None,
            last_name: None,
        }
    }
}
