/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReportsList {
    #[serde(rename = "reports", skip_serializing_if = "Option::is_none")]
    pub reports: Option<Vec<crate::models::Report>>,
}

impl ReportsList {
    pub fn new() -> ReportsList {
        ReportsList { reports: None }
    }
}
