/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RightToWorkBreakdownRightToWork : Asserts whether the applicant has the right to work.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownRightToWork {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::RightToWorkBreakdownRightToWorkBreakdown>>,
}

impl RightToWorkBreakdownRightToWork {
    /// Asserts whether the applicant has the right to work.
    pub fn new() -> RightToWorkBreakdownRightToWork {
        RightToWorkBreakdownRightToWork {
            result: None,
            breakdown: None,
        }
    }
}
