/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RightToWorkBreakdownDataConsistency : Asserts whether data represented in multiple places on the document is consistent.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownDataConsistency {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::RightToWorkBreakdownDataConsistencyBreakdown>>,
}

impl RightToWorkBreakdownDataConsistency {
    /// Asserts whether data represented in multiple places on the document is consistent.
    pub fn new() -> RightToWorkBreakdownDataConsistency {
        RightToWorkBreakdownDataConsistency {
            result: None,
            breakdown: None,
        }
    }
}
