/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties {
    /// Flags if the document number is not the expected length and format for document.
    #[serde(rename = "document_number", skip_serializing_if = "Option::is_none")]
    pub document_number: Option<String>,
}

impl RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties {
    pub fn new() -> RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties {
        RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties {
            document_number: None,
        }
    }
}
