/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RightToWorkBreakdownShareCodeValidation : Asserts whether the applicant has a valid right to work share code. Only returned when a share code is provided.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownShareCodeValidation {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Box<crate::models::RightToWorkBreakdownShareCodeValidationBreakdown>>,
}

impl RightToWorkBreakdownShareCodeValidation {
    /// Asserts whether the applicant has a valid right to work share code. Only returned when a share code is provided.
    pub fn new() -> RightToWorkBreakdownShareCodeValidation {
        RightToWorkBreakdownShareCodeValidation {
            result: None,
            breakdown: None,
        }
    }
}
