/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RightToWorkProperties : Returns the information contained in the submitted document.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkProperties {
    #[serde(rename = "nationality", skip_serializing_if = "Option::is_none")]
    pub nationality: Option<String>,
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "issuing_country", skip_serializing_if = "Option::is_none")]
    pub issuing_country: Option<String>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "document_type", skip_serializing_if = "Option::is_none")]
    pub document_type: Option<String>,
    #[serde(rename = "document_numbers", skip_serializing_if = "Option::is_none")]
    pub document_numbers: Option<Vec<crate::models::DocumentPropertiesDocumentNumbers>>,
    #[serde(rename = "date_of_expiry", skip_serializing_if = "Option::is_none")]
    pub date_of_expiry: Option<String>,
    #[serde(rename = "date_of_birth", skip_serializing_if = "Option::is_none")]
    pub date_of_birth: Option<String>,
    #[serde(rename = "document_version", skip_serializing_if = "Option::is_none")]
    pub document_version: Option<String>,
    #[serde(rename = "issuing_date", skip_serializing_if = "Option::is_none")]
    pub issuing_date: Option<String>,
    #[serde(rename = "mrz_line1", skip_serializing_if = "Option::is_none")]
    pub mrz_line1: Option<String>,
    #[serde(rename = "mrz_line2", skip_serializing_if = "Option::is_none")]
    pub mrz_line2: Option<String>,
    #[serde(rename = "place_of_birth", skip_serializing_if = "Option::is_none")]
    pub place_of_birth: Option<String>,
    #[serde(rename = "issuing_authority", skip_serializing_if = "Option::is_none")]
    pub issuing_authority: Option<String>,
}

impl RightToWorkProperties {
    /// Returns the information contained in the submitted document.
    pub fn new() -> RightToWorkProperties {
        RightToWorkProperties {
            nationality: None,
            last_name: None,
            issuing_country: None,
            gender: None,
            first_name: None,
            document_type: None,
            document_numbers: None,
            date_of_expiry: None,
            date_of_birth: None,
            document_version: None,
            issuing_date: None,
            mrz_line1: None,
            mrz_line2: None,
            place_of_birth: None,
            issuing_authority: None,
        }
    }
}
