/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RightToWorkBreakdownRightToWorkBreakdownApplicantHasTheRightToWork : Asserts whether the applicant has the right to work, has restricted right to work or no right to work.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownRightToWorkBreakdownApplicantHasTheRightToWork {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl RightToWorkBreakdownRightToWorkBreakdownApplicantHasTheRightToWork {
    /// Asserts whether the applicant has the right to work, has restricted right to work or no right to work.
    pub fn new() -> RightToWorkBreakdownRightToWorkBreakdownApplicantHasTheRightToWork {
        RightToWorkBreakdownRightToWorkBreakdownApplicantHasTheRightToWork {
            result: None,
            properties: None,
        }
    }
}
