/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RightToWorkBreakdownShareCodeValidationBreakdownApplicantHasValidShareCode : Asserts whether the provided share code is valid.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownShareCodeValidationBreakdownApplicantHasValidShareCode {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl RightToWorkBreakdownShareCodeValidationBreakdownApplicantHasValidShareCode {
    /// Asserts whether the provided share code is valid.
    pub fn new() -> RightToWorkBreakdownShareCodeValidationBreakdownApplicantHasValidShareCode {
        RightToWorkBreakdownShareCodeValidationBreakdownApplicantHasValidShareCode {
            result: None,
            properties: None,
        }
    }
}
