/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownRightToWorkBreakdown {
    #[serde(
        rename = "applicant_has_the_right_to_work",
        skip_serializing_if = "Option::is_none"
    )]
    pub applicant_has_the_right_to_work: Option<
        Box<crate::models::RightToWorkBreakdownRightToWorkBreakdownApplicantHasTheRightToWork>,
    >,
}

impl RightToWorkBreakdownRightToWorkBreakdown {
    pub fn new() -> RightToWorkBreakdownRightToWorkBreakdown {
        RightToWorkBreakdownRightToWorkBreakdown {
            applicant_has_the_right_to_work: None,
        }
    }
}
