/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RightToWorkBreakdownShareCodeValidationBreakdownDocumentId : Contains the document ID number in the properties bag.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownShareCodeValidationBreakdownDocumentId {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<
        Box<crate::models::RightToWorkBreakdownShareCodeValidationBreakdownDocumentIdProperties>,
    >,
}

impl RightToWorkBreakdownShareCodeValidationBreakdownDocumentId {
    /// Contains the document ID number in the properties bag.
    pub fn new() -> RightToWorkBreakdownShareCodeValidationBreakdownDocumentId {
        RightToWorkBreakdownShareCodeValidationBreakdownDocumentId {
            result: None,
            properties: None,
        }
    }
}
