/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RightToWorkBreakdownShareCodeValidationBreakdownNameMatched : Asserts whether the applicant's given name matches the name on the share code results document.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownShareCodeValidationBreakdownNameMatched {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl RightToWorkBreakdownShareCodeValidationBreakdownNameMatched {
    /// Asserts whether the applicant's given name matches the name on the share code results document.
    pub fn new() -> RightToWorkBreakdownShareCodeValidationBreakdownNameMatched {
        RightToWorkBreakdownShareCodeValidationBreakdownNameMatched {
            result: None,
            properties: None,
        }
    }
}
