/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RightToWorkBreakdownDataValidationBreakdownDocumentNumbers {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<
        Box<crate::models::RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties>,
    >,
}

impl RightToWorkBreakdownDataValidationBreakdownDocumentNumbers {
    pub fn new() -> RightToWorkBreakdownDataValidationBreakdownDocumentNumbers {
        RightToWorkBreakdownDataValidationBreakdownDocumentNumbers {
            result: None,
            properties: None,
        }
    }
}
