/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SdkToken {
    /// The unique identifier of the applicant
    #[serde(rename = "applicant_id", skip_serializing_if = "Option::is_none")]
    pub applicant_id: Option<String>,
    /// The referrer URL pattern
    #[serde(rename = "referrer", skip_serializing_if = "Option::is_none")]
    pub referrer: Option<String>,
    /// The application ID (iOS or Android)
    #[serde(rename = "application_id", skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    /// Enterprise Feature - The URL to be used for the cross device flow of the Web SDK
    #[serde(rename = "cross_device_url", skip_serializing_if = "Option::is_none")]
    pub cross_device_url: Option<String>,
    /// The generated SDK token
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl SdkToken {
    pub fn new() -> SdkToken {
        SdkToken {
            applicant_id: None,
            referrer: None,
            application_id: None,
            cross_device_url: None,
            token: None,
        }
    }
}
