/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VideoReasons {
    /// Flags when evidence is found that a fake webcam was used.
    #[serde(rename = "fake_webcam", skip_serializing_if = "Option::is_none")]
    pub fake_webcam: Option<String>,
    /// Flags when evidence is found that the video was uploaded in an attempt to circumvent the randomness of the speaking and head turn challenges
    #[serde(rename = "challenge_reuse", skip_serializing_if = "Option::is_none")]
    pub challenge_reuse: Option<String>,
    /// Flags when evidence is found that an Android emulator was used.
    #[serde(rename = "emulator", skip_serializing_if = "Option::is_none")]
    pub emulator: Option<String>,
    /// Additional comma separated details such as the name of the fake webcam.
    #[serde(rename = "reasons", skip_serializing_if = "Option::is_none")]
    pub reasons: Option<String>,
}

impl VideoReasons {
    pub fn new() -> VideoReasons {
        VideoReasons {
            fake_webcam: None,
            challenge_reuse: None,
            emulator: None,
            reasons: None,
        }
    }
}
