/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// WatchlistEnhancedBreakdownSanction : Asserts if there are any records found in Government and International Organisations Sanctions Lists.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WatchlistEnhancedBreakdownSanction {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl WatchlistEnhancedBreakdownSanction {
    /// Asserts if there are any records found in Government and International Organisations Sanctions Lists.
    pub fn new() -> WatchlistEnhancedBreakdownSanction {
        WatchlistEnhancedBreakdownSanction { result: None }
    }
}
