/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// WatchlistEnhancedBreakdownMonitoredLists : Asserts if there are any records found in Law-Enforcement and Regulatory bodies Monitored Lists (including Terrorism, Money Laundering and Most Wanted lists).

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WatchlistEnhancedBreakdownMonitoredLists {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl WatchlistEnhancedBreakdownMonitoredLists {
    /// Asserts if there are any records found in Law-Enforcement and Regulatory bodies Monitored Lists (including Terrorism, Money Laundering and Most Wanted lists).
    pub fn new() -> WatchlistEnhancedBreakdownMonitoredLists {
        WatchlistEnhancedBreakdownMonitoredLists { result: None }
    }
}
