/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WatchlistEnhancedBreakdown {
    #[serde(
        rename = "politically_exposed_person",
        skip_serializing_if = "Option::is_none"
    )]
    pub politically_exposed_person:
        Option<Box<crate::models::WatchlistEnhancedBreakdownPoliticallyExposedPerson>>,
    #[serde(rename = "sanction", skip_serializing_if = "Option::is_none")]
    pub sanction: Option<Box<crate::models::WatchlistEnhancedBreakdownSanction>>,
    #[serde(rename = "adverse_media", skip_serializing_if = "Option::is_none")]
    pub adverse_media: Option<Box<crate::models::WatchlistEnhancedBreakdownAdverseMedia>>,
    #[serde(rename = "monitored_lists", skip_serializing_if = "Option::is_none")]
    pub monitored_lists: Option<Box<crate::models::WatchlistEnhancedBreakdownMonitoredLists>>,
}

impl WatchlistEnhancedBreakdown {
    pub fn new() -> WatchlistEnhancedBreakdown {
        WatchlistEnhancedBreakdown {
            politically_exposed_person: None,
            sanction: None,
            adverse_media: None,
            monitored_lists: None,
        }
    }
}
