/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WatchlistStandardBreakdown {
    #[serde(rename = "sanction", skip_serializing_if = "Option::is_none")]
    pub sanction: Option<Box<crate::models::WatchlistEnhancedBreakdownSanction>>,
    #[serde(
        rename = "politically_exposed_person",
        skip_serializing_if = "Option::is_none"
    )]
    pub politically_exposed_person:
        Option<Box<crate::models::WatchlistEnhancedBreakdownPoliticallyExposedPerson>>,
    #[serde(
        rename = "legal_and_regulatory_warnings",
        skip_serializing_if = "Option::is_none"
    )]
    pub legal_and_regulatory_warnings:
        Option<Box<crate::models::WatchlistEnhancedBreakdownMonitoredLists>>,
}

impl WatchlistStandardBreakdown {
    pub fn new() -> WatchlistStandardBreakdown {
        WatchlistStandardBreakdown {
            sanction: None,
            politically_exposed_person: None,
            legal_and_regulatory_warnings: None,
        }
    }
}
