/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// WatchlistEnhancedBreakdownPoliticallyExposedPerson : Asserts if there are any records found in the proprietary database of Politically Exposed Persons sourced from government lists, websites and other media sources.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WatchlistEnhancedBreakdownPoliticallyExposedPerson {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

impl WatchlistEnhancedBreakdownPoliticallyExposedPerson {
    /// Asserts if there are any records found in the proprietary database of Politically Exposed Persons sourced from government lists, websites and other media sources.
    pub fn new() -> WatchlistEnhancedBreakdownPoliticallyExposedPerson {
        WatchlistEnhancedBreakdownPoliticallyExposedPerson { result: None }
    }
}
