/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WatchlistStandardProperties {
    /// Returns any matches including, but not limited to, name and date of birth of match, aliases and associates, and relevant events and sources.
    #[serde(rename = "records", skip_serializing_if = "Option::is_none")]
    pub records: Option<Vec<String>>,
}

impl WatchlistStandardProperties {
    pub fn new() -> WatchlistStandardProperties {
        WatchlistStandardProperties { records: None }
    }
}
